## Example 01
- Take 2 lists and multiply both you’ll see that error occurs repeat the process but by  coverting them toarray by numpy.array()

In [4]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1)
A2 = np.array(l2)

print(f"{A1} * {A2} = {A1*A2}")

[1 2 3] * [4 5 6] = [ 4 10 18]


### Example 02

- Demonstrate the use of numpy.dtype and numpy.shape() functions

In [5]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1)
A2 = np.array(l2)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (3,)


#example 3


In [7]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1, np.int8)
A2 = np.array(l2, np.int8)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int8
The dimension of an array: (3,)


#example 4

In [8]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A = np.array((l1, l2))
print(f" The 2D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The 2D array is : 
 [[1 2 3]
 [4 5 6]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (2, 3)
The size of an array: 6


#example 5

In [9]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1, np.int8)
A2 = np.array(l2, np.int8)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int8
The dimension of an array: (3,)
The size of an array: 3


#example 6

In [10]:
A = np.array(([1,2,3,4,5]))
print(f" The 1D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubut

 The 1D array is : 
 [1 2 3 4 5]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (5,)
The size of an array: 5


#EXAMPLE 7

In [11]:
import numpy as np

A = np.array(([1,2,3,4,5], [2,3,4,5,6]))
print(f" The 2D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute

 The 2D array is : 
 [[1 2 3 4 5]
 [2 3 4 5 6]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (2, 5)
The size of an array: 10


#EXAMPLE 8

In [12]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

 The array is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (4, 4)


#EXAMPLE 9

In [13]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The original array is : \n {A}")

A[1,2] = 10
print(f" The array after replacing : \n {A}")

 The original array is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The array after replacing : 
 [[ 1  2  3  4]
 [ 3  6 10  4]
 [ 1  2  9  4]
 [ 1  4  5  4]]


#EXAMPLE 10

In [14]:
import numpy as np

A = np.zeros([5,5])
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubut

 The array is : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5, 5)
The size of an array: 25


example 11

In [2]:
import numpy as np

A = np.zeros([5])
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is : 
 [0. 0. 0. 0. 0.]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5,)
The size of an array: 5
